services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: library-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_password123"
    ports:
      - "14333:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P $$MSSQL_SA_PASSWORD -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
